ARG VERSION

# --------------------------------------------------------------------------------------------------
# Builder Image
# --------------------------------------------------------------------------------------------------
FROM ghcr.io/mullholland/ansible:${VERSION}-tools as builder
ARG VERSION

# Make sure we use the virtualenv:
ENV PATH="/ansible/bin:$PATH"

RUN set -eux \
    && apk add --no-cache \
       # build tools
       coreutils \
       g++ \
       gcc \
       make \
       musl-dev \
       openssl-dev \
       python3-dev \
       # misc tools
       git \
       # go tools
       cargo \
       go


COPY Dockerfiles/requirements-ionos.txt /tmp
ENV IAM_AUTHENTICATOR_VERSION="0.6.10"
RUN set -eux \
    && pip3 install --no-cache-dir -r /tmp/requirements-ionos.txt \
    # Smoketest
    && if [ "${VERSION}" != "latest" ]; then \
       ansible --version | grep ^ansible | grep -E "${VERSION}\.[0-9]+" \
       && ansible-playbook --version | grep ^ansible | grep -E "${VERSION}\.[0-9]+" \
       && ansible-galaxy --version | grep ^ansible | grep -E "${VERSION}\.[0-9]+"; \
    else \
       ansible --version \
       && ansible-playbook --version \
       && ansible-galaxy --version; \
    fi

# --------------------------------------------------------------------------------------------------
# Final Image
# --------------------------------------------------------------------------------------------------
FROM ghcr.io/mullholland/ansible:${VERSION}-tools as production
ARG VERSION

LABEL "maintainer"="mullholland <mullholland@surprise-adoption.de>"
LABEL "org.opencontainers.image.authors"="mullholland <mullholland@surprise-adoption.de>"
LABEL "org.opencontainers.image.vendor"="mullholland"
LABEL "org.opencontainers.image.licenses"="MIT"
LABEL "org.opencontainers.image.url"="https://github.com/mullholland/docker-ansible"
LABEL "org.opencontainers.image.documentation"="https://github.com/mullholland/docker-ansible"
LABEL "org.opencontainers.image.source"="https://github.com/mullholland/docker-ansible"
LABEL "org.opencontainers.image.ref.name"="Ansible ${VERSION} ionos"
LABEL "org.opencontainers.image.title"="Ansible ${VERSION} ionos"
LABEL "org.opencontainers.image.description"="Ansible ${VERSION} ionos"

COPY --from=builder /ansible /ansible
ARG IONOSCTL_VERSION="6.7.7"
RUN apk add --no-cache curl \
    && if [ "$(uname -m)" = "aarch64" ]; then \
      ARCH="arm64"; \
      curl -sL https://github.com/ionos-cloud/ionosctl/releases/download/v${IONOSCTL_VERSION}/ionosctl-${IONOSCTL_VERSION}-linux-${ARCH}.tar.gz | tar -xzv; \
    elif [ "$(uname -m)" = "x86_64" ]; then \
      ARCH="amd64"; \
      curl -sL https://github.com/ionos-cloud/ionosctl/releases/download/v${IONOSCTL_VERSION}/ionosctl-${IONOSCTL_VERSION}-linux-${ARCH}.tar.gz | tar -xzv; \
    else \
      fail; \
    fi \
    # Move the binary somewhere in your $PATH:
    && mv ionosctl /usr/local/bin \
    # Use the ionosctl CLI
    && ionosctl version

# Make sure we use the virtualenv:
ENV PATH="/ansible/bin:$PATH"

WORKDIR /ansible
CMD [ "ansible-playbook", "--version" ]
