---
name: Build and Push Container

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "10 2 * * *"  # nightly builds

jobs:
  # Test the image builds and works correctly.
  test-base:
    name: test-base
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - version:
              - "2.13"
              - "2.14"
              - "2.15"
              - "latest"
            type:
              - "base"

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: docker build -t docker-test --build-arg VERSION=${{ matrix.config.version }} -f Dockerfiles/Dockerfile-${{ matrix.config.type }} .

      - name: Verify ansible in the built image.
        run: |
          if [ "${{ matrix.config.version }}" = "latest" ];
            docker run --rm docker-test ansible --version | grep "core 2."
          else
            docker run --rm docker-test ansible --version | grep "core ${{ matrix.config.version }}"
          fi

  # If on master branch, build and release image.
  release-base:
    name: release-base
    runs-on: ubuntu-latest
    needs: test-base
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        config:
          - version:
              - "2.13"
              - "2.14"
              - "2.15"
              - "latest"
            type:
              - "base"

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfiles/Dockerfile-
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository }}:${{ matrix.config.version }}
            ghcr.io/${{ github.repository }}:${{ matrix.config.version }}
