---
name: build

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "10 2 * * *"  # nightly builds

jobs:
  # -------------------------------------
  # Test the image builds and works correctly.
  # -------------------------------------
  test-docker-builds:
    name: test-base
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - "2.13"
          - "2.14"
          - "2.15"
          - "latest"
        type:
          - "base"
          - "tools"
          - "infra"
          - "azure"
          - "aws"

    steps:
      - uses: actions/checkout@v3

      - name: Test building image.
        run: docker build -t docker-test --build-arg VERSION=${{ matrix.version }} -f Dockerfiles/Dockerfile-${{ matrix.type }} .

      - name: Verify ansible in the built image.
        run: |
          if [ "${{ matrix.version }}" = "latest" ]; then
            docker run --rm docker-test ansible --version | grep "core 2."
          else
            docker run --rm docker-test ansible --version | grep "core ${{ matrix.version }}"
          fi

  # -------------------------------------
  # If on master branch, build and release base image.
  # -------------------------------------
  release-base:
    name: release-base
    runs-on: ubuntu-latest
    needs: test-docker-builds
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        version:
          - "2.13"
          - "2.14"
          - "2.15"
          - "latest"
        type:
          - "base"

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfiles/Dockerfile-${{ matrix.type }}
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ matrix.version }}
          tags: |
            mullholland/ansible:${{ matrix.version }}
            ghcr.io/mullholland/ansible:${{ matrix.version }}

  # -------------------------------------
  # If on master branch, build and release tools image.
  # -------------------------------------
  release-tools:
    name: release-tools
    runs-on: ubuntu-latest
    needs: release-base
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        version:
          - "2.13"
          - "2.14"
          - "2.15"
          - "latest"
        type:
          - "tools"

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfiles/Dockerfile-${{ matrix.type }}
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ matrix.version }}
          tags: |
            mullholland/ansible:${{ matrix.version }}-${{ matrix.type }}
            ghcr.io/mullholland/ansible:${{ matrix.version }}-${{ matrix.type }}

  # -------------------------------------
  # If on master branch, build and release tools image.
  # -------------------------------------
  release-variants:
    name: release-variants
    runs-on: ubuntu-latest
    needs: release-tools
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        version:
          - "2.13"
          - "2.14"
          - "2.15"
          - "latest"
        type:
          - "infra"
          - "azure"
          - "aws"

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfiles/Dockerfile-${{ matrix.type }}
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ matrix.version }}
          tags: |
            mullholland/ansible:${{ matrix.version }}-${{ matrix.type }}
            ghcr.io/mullholland/ansible:${{ matrix.version }}-${{ matrix.type }}


  # -------------------------------------
  # Update version if everything builds correctly
  # -------------------------------------
  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - release-base
      - release-tools
      - release-variants
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-generator-opt: "emojis=true"
